import { LoadersProvider } from "@/utils/LoadersProvider";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import IsLoading from "@/utils/IsLoading";
import Loader from "@/components/Loader";
import { UserServiceProvider } from "@/services/UserServiceProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <LoadersProvider>
          <UserServiceProvider>
          <IsLoading loaderId="main">
            <Loader />
          </IsLoading>
          {children}
          </UserServiceProvider>
        </LoadersProvider>
      </body>
    </html>
  );
}
